#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

language: cpp
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - g++-4.8
            - gnupg
            - libclang-dev
            - clang-3.7
            - emacs

git:
  depth: 3

matrix:
    include:
        - os: linux
          compiler: g++
          dist: trusty
          env: "g++ linux"
        - os: linux
          compiler: clang
          dist: trusty
          env: "g++ clang"
        - os: osx
          compiler: g++
          env: "g++ linux"
        - os: osx
          compiler: clang
          env: "clang osx"

install:
    - pip install --user --upgrade nose
    - pip install --user --upgrade PyHamcrest
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install llvm cmake openssl; fi

branches:
    only:
        - master

script: ./scripts/travis.sh
