#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: required
dist: trusty
group: deprecated-2017Q4

language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - g++-4.8
            - gnupg
            - libclang-dev
            - clang-3.7
            - emacs

git:
  depth: 3

matrix:
  include:
    - env: COMPILER_VERSION=4.8
      os: linux
      compiler: g++
    - env: COMPILER_VERSION=3.7
      os: linux
      compiler: clang++

install:
  - pip install --user --upgrade nose
  - pip install --user --upgrade PyHamcrest

script: ./scripts/travis.sh
