#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

language: cpp
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
        packages:
            - g++-4.8
            - gnupg
            - libclang-5.0-dev
            - clang-5.0
            - build-essential
            - emacs

git:
  depth: 3

matrix:
    include:
        - os: linux
          compiler: g++
          dist: trusty
          env: T=g++-linux COMPILER_VERSION=4.8
        - os: linux
          compiler: clang
          dist: trusty
          env: T=g++-clang COMPILER_VERSION=5.0
        - os: osx
          compiler: g++
          env: T=g++-osx
        - os: osx
          compiler: clang
          env: T=clang-osx

branches:
    only:
        - master

script: ./scripts/travis.sh
